//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/07/04 - 12:32:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="staffmarkingdetail"/> and <see cref="staffmarkingdetailDto"/>.
    /// </summary>
    public static partial class staffmarkingdetailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="staffmarkingdetailDto"/> converted from <see cref="staffmarkingdetail"/>.</param>
        static partial void OnDTO(this staffmarkingdetail entity, staffmarkingdetailDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="staffmarkingdetail"/> converted from <see cref="staffmarkingdetailDto"/>.</param>
        static partial void OnEntity(this staffmarkingdetailDto dto, staffmarkingdetail entity);

        /// <summary>
        /// Converts this instance of <see cref="staffmarkingdetailDto"/> to an instance of <see cref="staffmarkingdetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="staffmarkingdetailDto"/> to convert.</param>
        public static staffmarkingdetail ToEntity(this staffmarkingdetailDto dto)
        {
            if (dto == null) return null;

            var entity = new staffmarkingdetail();

            entity.v_RegistrationDetailId = dto.v_RegistrationDetailId;
            entity.v_PersonId = dto.v_PersonId;
            entity.d_Date = dto.d_Date;
            entity.t_FirstDial = dto.t_FirstDial;
            entity.t_SecondDial = dto.t_SecondDial;
            entity.t_ThridDial = dto.t_ThridDial;
            entity.t_FourthDial = dto.t_FourthDial;
            entity.i_TotalDialing = dto.i_TotalDialing;
            entity.t_TimeOfEntry = dto.t_TimeOfEntry;
            entity.t_DepartureTime = dto.t_DepartureTime;
            entity.i_Double = dto.i_Double;
            entity.i_IsProcessed = dto.i_IsProcessed;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="staffmarkingdetail"/> to an instance of <see cref="staffmarkingdetailDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="staffmarkingdetail"/> to convert.</param>
        public static staffmarkingdetailDto ToDTO(this staffmarkingdetail entity)
        {
            if (entity == null) return null;

            var dto = new staffmarkingdetailDto();

            dto.v_RegistrationDetailId = entity.v_RegistrationDetailId;
            dto.v_PersonId = entity.v_PersonId;
            dto.d_Date = entity.d_Date;
            dto.t_FirstDial = entity.t_FirstDial;
            dto.t_SecondDial = entity.t_SecondDial;
            dto.t_ThridDial = entity.t_ThridDial;
            dto.t_FourthDial = entity.t_FourthDial;
            dto.i_TotalDialing = entity.i_TotalDialing;
            dto.t_TimeOfEntry = entity.t_TimeOfEntry;
            dto.t_DepartureTime = entity.t_DepartureTime;
            dto.i_Double = entity.i_Double;
            dto.i_IsProcessed = entity.i_IsProcessed;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="staffmarkingdetailDto"/> to an instance of <see cref="staffmarkingdetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<staffmarkingdetail> ToEntities(this IEnumerable<staffmarkingdetailDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="staffmarkingdetail"/> to an instance of <see cref="staffmarkingdetailDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<staffmarkingdetailDto> ToDTOs(this IEnumerable<staffmarkingdetail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
