//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2019/07/04 - 12:32:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="staffovertime"/> and <see cref="staffovertimeDto"/>.
    /// </summary>
    public static partial class staffovertimeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="staffovertimeDto"/> converted from <see cref="staffovertime"/>.</param>
        static partial void OnDTO(this staffovertime entity, staffovertimeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="staffovertime"/> converted from <see cref="staffovertimeDto"/>.</param>
        static partial void OnEntity(this staffovertimeDto dto, staffovertime entity);

        /// <summary>
        /// Converts this instance of <see cref="staffovertimeDto"/> to an instance of <see cref="staffovertime"/>.
        /// </summary>
        /// <param name="dto"><see cref="staffovertimeDto"/> to convert.</param>
        public static staffovertime ToEntity(this staffovertimeDto dto)
        {
            if (dto == null) return null;

            var entity = new staffovertime();

            entity.v_PersonId = dto.v_PersonId;
            entity.r_OverTime25 = dto.r_OverTime25;
            entity.r_OverTime35 = dto.r_OverTime35;
            entity.r_OverTimeDouble = dto.r_OverTimeDouble;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="staffovertime"/> to an instance of <see cref="staffovertimeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="staffovertime"/> to convert.</param>
        public static staffovertimeDto ToDTO(this staffovertime entity)
        {
            if (entity == null) return null;

            var dto = new staffovertimeDto();

            dto.v_PersonId = entity.v_PersonId;
            dto.r_OverTime25 = entity.r_OverTime25;
            dto.r_OverTime35 = entity.r_OverTime35;
            dto.r_OverTimeDouble = entity.r_OverTimeDouble;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="staffovertimeDto"/> to an instance of <see cref="staffovertime"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<staffovertime> ToEntities(this IEnumerable<staffovertimeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="staffovertime"/> to an instance of <see cref="staffovertimeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<staffovertimeDto> ToDTOs(this IEnumerable<staffovertime> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
