//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2022/08/03 - 23:17:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="historyclinicsdetail"/> and <see cref="historyclinicsdetailDto"/>.
    /// </summary>
    public static partial class historyclinicsdetailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="historyclinicsdetailDto"/> converted from <see cref="historyclinicsdetail"/>.</param>
        static partial void OnDTO(this historyclinicsdetail entity, historyclinicsdetailDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="historyclinicsdetail"/> converted from <see cref="historyclinicsdetailDto"/>.</param>
        static partial void OnEntity(this historyclinicsdetailDto dto, historyclinicsdetail entity);

        /// <summary>
        /// Converts this instance of <see cref="historyclinicsdetailDto"/> to an instance of <see cref="historyclinicsdetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="historyclinicsdetailDto"/> to convert.</param>
        public static historyclinicsdetail ToEntity(this historyclinicsdetailDto dto)
        {
            if (dto == null) return null;

            var entity = new historyclinicsdetail();

            entity.v_HServiceId = dto.v_HServiceId;
            entity.v_nroHistoria = dto.v_nroHistoria;
            entity.v_ServiceId = dto.v_ServiceId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="historyclinicsdetail"/> to an instance of <see cref="historyclinicsdetailDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="historyclinicsdetail"/> to convert.</param>
        public static historyclinicsdetailDto ToDTO(this historyclinicsdetail entity)
        {
            if (entity == null) return null;

            var dto = new historyclinicsdetailDto();

            dto.v_HServiceId = entity.v_HServiceId;
            dto.v_nroHistoria = entity.v_nroHistoria;
            dto.v_ServiceId = entity.v_ServiceId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="historyclinicsdetailDto"/> to an instance of <see cref="historyclinicsdetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<historyclinicsdetail> ToEntities(this IEnumerable<historyclinicsdetailDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="historyclinicsdetail"/> to an instance of <see cref="historyclinicsdetailDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<historyclinicsdetailDto> ToDTOs(this IEnumerable<historyclinicsdetail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
